"""Atlas ingestion — the source contract and the first two stages of the funnel.

Reading order: :mod:`~atlas.ingestion.registry` (what Atlas may read), then
:mod:`~atlas.ingestion.contracts` (what a source is), then
:mod:`~atlas.ingestion.idempotency` (stage 0, ADR-0007), then
:mod:`~atlas.ingestion.triage` (stage 1, the exposure gate), then
:mod:`~atlas.ingestion.pipeline` (the two composed into an auditable record).

Nothing in this package calls a model, writes to a provider, or reads the wall clock.
"""

from atlas.ingestion.contracts import (
    AdapterDescriptor,
    AdapterError,
    AdapterFailure,
    CursorRegression,
    FetchBatch,
    FetchedItem,
    FetchWindow,
    MalformedItem,
    SourceAdapter,
    SourceAuthenticationError,
    SourceContractViolation,
    SourceCursor,
    SourceNotPermitted,
    SourceRateLimited,
    SourceTimeout,
    SourceUnavailable,
    collect,
)
from atlas.ingestion.idempotency import (
    DedupeLayer,
    DedupeStatus,
    DedupeVerdict,
    Deduplicator,
    InMemoryLedger,
    ItemIdentity,
    SeenLedger,
    canonical_url,
    content_hash,
    identify,
    normalise_text,
)
from atlas.ingestion.pipeline import (
    AdmittedItem,
    DroppedItem,
    IngestionReport,
    ingest,
    raw_item_id,
    run_counts,
    run_gaps,
    to_raw_item,
)
from atlas.ingestion.registry import (
    CATALOGUE,
    REGISTRY,
    AccessMode,
    SourceKind,
    SourceRegistry,
    SourceSpec,
    VerificationStatus,
)
from atlas.ingestion.triage import (
    ExposureGate,
    ExposureKind,
    ExposureMatch,
    ExposureProfile,
    ExposureTerm,
    GatePolicy,
    MatchMode,
    TriageDecision,
    TriageOutcome,
    TriageStage,
    exposure_score,
)

__all__ = [
    "CATALOGUE",
    "REGISTRY",
    "AccessMode",
    "AdapterDescriptor",
    "AdapterError",
    "AdapterFailure",
    "AdmittedItem",
    "CursorRegression",
    "DedupeLayer",
    "DedupeStatus",
    "DedupeVerdict",
    "Deduplicator",
    "DroppedItem",
    "ExposureGate",
    "ExposureKind",
    "ExposureMatch",
    "ExposureProfile",
    "ExposureTerm",
    "FetchBatch",
    "FetchWindow",
    "FetchedItem",
    "GatePolicy",
    "InMemoryLedger",
    "IngestionReport",
    "ItemIdentity",
    "MalformedItem",
    "MatchMode",
    "SeenLedger",
    "SourceAdapter",
    "SourceAuthenticationError",
    "SourceContractViolation",
    "SourceCursor",
    "SourceKind",
    "SourceNotPermitted",
    "SourceRateLimited",
    "SourceRegistry",
    "SourceSpec",
    "SourceTimeout",
    "SourceUnavailable",
    "TriageDecision",
    "TriageOutcome",
    "TriageStage",
    "VerificationStatus",
    "canonical_url",
    "collect",
    "content_hash",
    "exposure_score",
    "identify",
    "ingest",
    "normalise_text",
    "raw_item_id",
    "run_counts",
    "run_gaps",
    "to_raw_item",
]
