"""queue 01 persistence foundation

Revision ID: 0caec4550b85
Revises:
Create Date: 2026-08-28 19:17:40.097695
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0caec4550b85"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("canonical_title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_reported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("geography", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("entities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sectors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("credibility_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("novelty_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("urgency_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("dedupe_key", sa.String(length=128), nullable=False),
        sa.Column(
            "effective_tier",
            sa.Enum(
                "L0",
                "L1",
                "L2",
                "L3",
                name="sensitivity_tier",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "credibility_score BETWEEN 0 AND 1", name=op.f("ck_events_credibility_bounds")
        ),
        sa.CheckConstraint("novelty_score BETWEEN 0 AND 1", name=op.f("ck_events_novelty_bounds")),
        sa.CheckConstraint("urgency_score BETWEEN 0 AND 1", name=op.f("ck_events_urgency_bounds")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_events_dedupe_key")),
    )
    op.create_table(
        "forecast_questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("domain_key", sa.String(length=100), nullable=False),
        sa.Column("resolution_criteria", sa.Text(), nullable=False),
        sa.Column("resolve_by", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "RESOLVED",
                "CANCELLED",
                name="forecastquestionstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "effective_tier",
            sa.Enum(
                "L0",
                "L1",
                "L2",
                "L3",
                name="sensitivity_tier",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(resolution_criteria)) > 0",
            name=op.f("ck_forecast_questions_criteria_required"),
        ),
        sa.CheckConstraint(
            "resolve_by > created_at", name=op.f("ck_forecast_questions_resolve_after_creation")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_questions")),
    )
    op.create_table(
        "narratives",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("direction", sa.String(length=40), nullable=False),
        sa.Column("strength", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_confirmed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "effective_tier",
            sa.Enum(
                "L0",
                "L1",
                "L2",
                "L3",
                name="sensitivity_tier",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name=op.f("ck_narratives_confidence_bounds")
        ),
        sa.CheckConstraint("strength BETWEEN 0 AND 1", name=op.f("ck_narratives_strength_bounds")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_narratives")),
        sa.UniqueConstraint("slug", name=op.f("uq_narratives_slug")),
    )
    op.create_table(
        "objectives",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category_key", sa.String(length=100), nullable=False),
        sa.Column(
            "direction",
            sa.Enum(
                "ATTAIN",
                "AVOID",
                "MAINTAIN",
                name="objectivedirection",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "horizon",
            sa.Enum(
                "SHORT",
                "MEDIUM",
                "LONG",
                name="objectivehorizon",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("target_value", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("target_currency", sa.String(length=3), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ACTIVE",
                "ACHIEVED",
                "ABANDONED",
                "INACTIVE",
                "SUPERSEDED",
                name="objectivestatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "authored_by",
            sa.Enum(
                "OWNER",
                "ATLAS_PROPOSED",
                name="authoredby",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "effective_tier",
            sa.Enum(
                "L0",
                "L1",
                "L2",
                "L3",
                name="sensitivity_tier",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'ACTIVE' OR accepted_at IS NOT NULL",
            name=op.f("ck_objectives_active_requires_acceptance"),
        ),
        sa.CheckConstraint("priority >= 0", name=op.f("ck_objectives_priority_nonnegative")),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name=op.f("ck_objectives_valid_interval")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_objectives")),
    )
    op.create_index(op.f("ix_objectives_owner_id"), "objectives", ["owner_id"], unique=False)
    op.create_index(op.f("ix_objectives_valid_from"), "objectives", ["valid_from"], unique=False)
    op.create_index(op.f("ix_objectives_valid_to"), "objectives", ["valid_to"], unique=False)
    op.create_table(
        "run_records",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_calls", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cost", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("deltas_created", sa.Integer(), nullable=False),
        sa.Column("alerts_emitted", sa.Integer(), nullable=False),
        sa.Column("missing_critical_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "effective_tier",
            sa.Enum(
                "L0",
                "L1",
                "L2",
                "L3",
                name="sensitivity_tier",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.CheckConstraint("cost >= 0", name=op.f("ck_run_records_cost_nonnegative")),
        sa.CheckConstraint("latency_ms >= 0", name=op.f("ck_run_records_latency_nonnegative")),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_run_records")),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("source_type", sa.String(length=80), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("jurisdiction", sa.String(length=32), nullable=True),
        sa.Column("default_reliability", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("latency_class", sa.String(length=40), nullable=False),
        sa.Column("terms_notes", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "effective_tier",
            sa.Enum(
                "L0",
                "L1",
                "L2",
                "L3",
                name="sensitivity_tier",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "default_reliability >= 0 AND default_reliability <= 1",
            name=op.f("ck_sources_default_reliability_bounds"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
    )
    op.create_table(
        "forecast_predictions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column(
            "forecaster_type",
            sa.Enum(
                "OWNER", "ATLAS", name="forecastertype", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("probability", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("made_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_ref", sa.Text(), nullable=True),
        sa.Column(
            "prompt_or_artifact_version_refs",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("supersedes_prediction_id", sa.UUID(), nullable=True),
        sa.Column(
            "effective_tier",
            sa.Enum(
                "L0",
                "L1",
                "L2",
                "L3",
                name="sensitivity_tier",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(forecaster_type = 'ATLAS' AND model_ref IS NOT NULL) OR "
            "(forecaster_type = 'OWNER' AND model_ref IS NULL)",
            name=op.f("ck_forecast_predictions_model_ref_matches_forecaster"),
        ),
        sa.CheckConstraint(
            "probability >= 0 AND probability <= 1",
            name=op.f("ck_forecast_predictions_probability_bounds"),
        ),
        sa.CheckConstraint(
            "supersedes_prediction_id IS NULL OR supersedes_prediction_id <> id",
            name=op.f("ck_forecast_predictions_does_not_supersede_self"),
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["forecast_questions.id"],
            name=op.f("fk_forecast_predictions_question_id_forecast_questions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_prediction_id"],
            ["forecast_predictions.id"],
            name=op.f("fk_forecast_predictions_supersedes_prediction_id_forecast_predictions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_predictions")),
    )
    op.create_index(
        op.f("ix_forecast_predictions_question_id"),
        "forecast_predictions",
        ["question_id"],
        unique=False,
    )
    op.create_table(
        "forecast_resolutions",
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("outcome", sa.Boolean(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column(
            "effective_tier",
            sa.Enum(
                "L0",
                "L1",
                "L2",
                "L3",
                name="sensitivity_tier",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["forecast_questions.id"],
            name=op.f("fk_forecast_resolutions_question_id_forecast_questions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("question_id", name=op.f("pk_forecast_resolutions")),
    )
    op.create_table(
        "narrative_events",
        sa.Column("narrative_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_narrative_events_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["narrative_id"],
            ["narratives.id"],
            name=op.f("fk_narrative_events_narrative_id_narratives"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("narrative_id", "event_id", name=op.f("pk_narrative_events")),
    )
    op.create_table(
        "preferences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("higher_objective_id", sa.UUID(), nullable=False),
        sa.Column("lower_objective_id", sa.UUID(), nullable=False),
        sa.Column(
            "strength",
            sa.Enum(
                "WEAK",
                "STRONG",
                name="preferencestrength",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column(
            "authored_by",
            sa.Enum(
                "OWNER",
                "ATLAS_PROPOSED",
                name="authoredby",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ACTIVE",
                "INACTIVE",
                "SUPERSEDED",
                name="preferencestatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "effective_tier",
            sa.Enum(
                "L0",
                "L1",
                "L2",
                "L3",
                name="sensitivity_tier",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'ACTIVE' OR accepted_at IS NOT NULL",
            name=op.f("ck_preferences_active_requires_acceptance"),
        ),
        sa.CheckConstraint(
            "higher_objective_id <> lower_objective_id",
            name=op.f("ck_preferences_different_objectives"),
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name=op.f("ck_preferences_valid_interval")
        ),
        sa.ForeignKeyConstraint(
            ["higher_objective_id"],
            ["objectives.id"],
            name=op.f("fk_preferences_higher_objective_id_objectives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["lower_objective_id"],
            ["objectives.id"],
            name=op.f("fk_preferences_lower_objective_id_objectives"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preferences")),
    )
    op.create_index(op.f("ix_preferences_owner_id"), "preferences", ["owner_id"], unique=False)
    op.create_index(op.f("ix_preferences_valid_from"), "preferences", ["valid_from"], unique=False)
    op.create_index(op.f("ix_preferences_valid_to"), "preferences", ["valid_to"], unique=False)
    op.create_table(
        "raw_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("parse_version", sa.String(length=80), nullable=False),
        sa.Column(
            "effective_tier",
            sa.Enum(
                "L0",
                "L1",
                "L2",
                "L3",
                name="sensitivity_tier",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_raw_items_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_items")),
        sa.UniqueConstraint("content_hash", name=op.f("uq_raw_items_content_hash")),
        sa.UniqueConstraint("source_id", "external_id", name="source_external_id"),
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raw_item_id", sa.UUID(), nullable=False),
        sa.Column("proposition", sa.Text(), nullable=False),
        sa.Column("evidence_type", sa.String(length=80), nullable=False),
        sa.Column("entities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_reliability", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("extraction_confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("verification_status", sa.String(length=40), nullable=False),
        sa.Column("structured_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "effective_tier",
            sa.Enum(
                "L0",
                "L1",
                "L2",
                "L3",
                name="sensitivity_tier",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "extraction_confidence >= 0 AND extraction_confidence <= 1",
            name=op.f("ck_evidence_extraction_confidence_bounds"),
        ),
        sa.CheckConstraint(
            "source_reliability >= 0 AND source_reliability <= 1",
            name=op.f("ck_evidence_source_reliability_bounds"),
        ),
        sa.ForeignKeyConstraint(
            ["raw_item_id"],
            ["raw_items.id"],
            name=op.f("fk_evidence_raw_item_id_raw_items"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
    )
    op.create_table(
        "event_evidence",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_evidence_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_event_evidence_evidence_id_evidence"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("event_id", "evidence_id", name=op.f("pk_event_evidence")),
    )
    op.create_table(
        "forecast_prediction_evidence",
        sa.Column("prediction_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_forecast_prediction_evidence_evidence_id_evidence"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["forecast_predictions.id"],
            name=op.f("fk_forecast_prediction_evidence_prediction_id_forecast_predictions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "prediction_id", "evidence_id", name=op.f("pk_forecast_prediction_evidence")
        ),
    )
    op.create_table(
        "forecast_resolution_evidence",
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_forecast_resolution_evidence_evidence_id_evidence"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["forecast_resolutions.question_id"],
            name=op.f("fk_forecast_resolution_evidence_question_id_forecast_resolutions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "question_id", "evidence_id", name=op.f("pk_forecast_resolution_evidence")
        ),
    )
    op.execute(
        """
        CREATE FUNCTION atlas_reject_forecast_prediction_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'forecast predictions are append-only'
                USING ERRCODE = '55000';
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER forecast_predictions_append_only
        BEFORE UPDATE OR DELETE ON forecast_predictions
        FOR EACH ROW
        EXECUTE FUNCTION atlas_reject_forecast_prediction_mutation()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER forecast_predictions_append_only ON forecast_predictions")
    op.execute("DROP FUNCTION atlas_reject_forecast_prediction_mutation()")
    op.drop_table("forecast_resolution_evidence")
    op.drop_table("forecast_prediction_evidence")
    op.drop_table("event_evidence")
    op.drop_table("evidence")
    op.drop_table("raw_items")
    op.drop_index(op.f("ix_preferences_valid_to"), table_name="preferences")
    op.drop_index(op.f("ix_preferences_valid_from"), table_name="preferences")
    op.drop_index(op.f("ix_preferences_owner_id"), table_name="preferences")
    op.drop_table("preferences")
    op.drop_table("narrative_events")
    op.drop_table("forecast_resolutions")
    op.drop_index(op.f("ix_forecast_predictions_question_id"), table_name="forecast_predictions")
    op.drop_table("forecast_predictions")
    op.drop_table("sources")
    op.drop_table("run_records")
    op.drop_index(op.f("ix_objectives_valid_to"), table_name="objectives")
    op.drop_index(op.f("ix_objectives_valid_from"), table_name="objectives")
    op.drop_index(op.f("ix_objectives_owner_id"), table_name="objectives")
    op.drop_table("objectives")
    op.drop_table("narratives")
    op.drop_table("forecast_questions")
    op.drop_table("events")
    # ### end Alembic commands ###
